{{- if and .Values.listen.enabled .Values.listen.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "compactor.fullname" . }}
  labels:
    {{- include "compactor.labels" . | nindent 4 }}
    app.kubernetes.io/component: listen
spec:
  {{- with .Values.listen.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.listen.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "compactor.listenSelectorLabels" . | nindent 6 }}
{{- end }}
