{{- if include "compactor.createCredentialsSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compactor.credentialsSecretName" . }}
  labels:
    {{- include "compactor.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ required "credentials.accessKeyId is required when credentials.secretAccessKey is set" .Values.credentials.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "credentials.secretAccessKey is required when credentials.accessKeyId is set" .Values.credentials.secretAccessKey | quote }}
{{- end }}
