# bash completion for compactor
# generated by king (https://github.com/miekg/king) for kong

_compactor_filter() {
  COMP_REPLY=()
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done
    echo "${result[*]}"
  fi
}

_compactor_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in

    'rollup promote-month'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--month")" -- "$cur")
      ;;
    'rollup promote-week'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--week")" -- "$cur")
      ;;
    'checkpoint reset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--day --week --month --confirm")" -- "$cur")
      ;;
    'completions bash'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--output -o")" -- "$cur")
      ;;
    'completions fish'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--output -o")" -- "$cur")
      ;;
    'checkpoint show'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--day --week --month")" -- "$cur")
      ;;
    'completions zsh'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--output -o")" -- "$cur")
      ;;
    'rollup hourly'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--day")" -- "$cur")
      ;;
    'completions'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "bash zsh fish")" -- "$cur")
      ;;
    'materialize'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--out --keep ")" -- "$cur")
      ;;
    'checkpoint'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "show reset")" -- "$cur")
      ;;
    'listen'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "")" -- "$cur")
      ;;
    'rollup'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "hourly promote-week promote-month")" -- "$cur")
      ;;
    'man'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "--output -o")" -- "$cur")
      ;;
    ''*'--encryption-scheme')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "none age")" -- "$cur")
      ;;
    ''*'--logging-level')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "debug info warn error")" -- "$cur")
      ;;
    ''*'--logging-format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "text json")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_compactor_filter "rollup materialize checkpoint listen man completions --help -h --config --s3-endpoint --s3-region --s3-bucket --s3-use-path-style --paths-source-prefix --paths-rollup-prefix --paths-checkpoint-prefix --encryption-scheme --encryption-age-recipients --encryption-age-identity-file --rollup-straggler-days --rollup-week-start --materialize-cache-ttl --listen-nats-url --listen-nats-stream --listen-nats-subject --listen-nats-consumer --listen-http-addr --listen-debounce --logging-level --logging-format --version")" -- "$cur")
      ;;
esac

} &&
complete -F _compactor_completions compactor
