# fish shell completion for compactor
# generated by king (https://github.com/miekg/king) for kong
# compactor
complete -c compactor -f -s h -l help -d "Show context-sensitive help."
complete -c compactor -f -x -l config -d "Path to YAML config file (default: XDG config dir)."
complete -c compactor -f -x -l s3-endpoint -d "S3 endpoint (empty = AWS default; set for MinIO, e.g. http://localhost:9000)."
complete -c compactor -f -x -l s3-region -d "AWS region."
complete -c compactor -f -x -l s3-bucket -d "Bucket name."
complete -c compactor -f -l s3-use-path-style -d "Use path-style S3 addressing (most MinIO deployments)."
complete -c compactor -f -x -l paths-source-prefix -d "Base prefix under which year/month/day raw events live."
complete -c compactor -f -x -l paths-rollup-prefix -d "Rollup key prefix."
complete -c compactor -f -x -l paths-checkpoint-prefix -d "Checkpoint key prefix."
complete -c compactor -f -xa 'none age' -l encryption-scheme -d "Rollup output scheme."
complete -c compactor -f -x -l encryption-age-recipients -d "age1... recipient public keys."
complete -c compactor -f -x -l encryption-age-identity-file -d "Path to age identity file (required for decrypt/materialize)."
complete -c compactor -f -x -l rollup-straggler-days -d "Also re-check N prior days on every hourly run."
complete -c compactor -f -x -l rollup-week-start -d "Reserved; ISO 8601 (Monday-start) weeks are used today."
complete -c compactor -f -x -l materialize-cache-ttl -d "Materialized scratch file TTL, for the expiry sweep."
complete -c compactor -f -x -l listen-nats-url -d "NATS server URL."
complete -c compactor -f -x -l listen-nats-stream -d "JetStream stream MinIO's NATS notification target publishes to."
complete -c compactor -f -x -l listen-nats-subject -d "Filter subject within the stream."
complete -c compactor -f -x -l listen-nats-consumer -d "Durable JetStream consumer name."
complete -c compactor -f -x -l listen-http-addr -d "Address to serve /healthz and /readyz on."
complete -c compactor -f -x -l listen-debounce -d "Coalesce a burst of notifications for one day into a single reconcile."
complete -c compactor -f -xa 'debug info warn error' -l logging-level -d "Log level."
complete -c compactor -f -xa 'text json' -l logging-format -d "Log format."
complete -c compactor -f -l version -d "Print version and exit."

# rollup
complete -c compactor -f -n '__fish_use_subcommand' -a rollup -d 'Roll up source events into day/week/month JSONL.'

# rollup hourly
complete -c compactor -f -n '__fish_use_subcommand' -a hourly -d 'Incremental day rollup (current day + configured stragglers).'
complete -c compactor -f -n '__fish_seen_subcommand_from hourly' -x -l day -d "Day to process (YYYY-MM-DD); default: today plus configured straggler days."

# rollup promote-week
complete -c compactor -f -n '__fish_use_subcommand' -a promote-week -d 'Rebuild a week rollup from its day rollups.'
complete -c compactor -f -n '__fish_seen_subcommand_from promote-week' -x -l week -d "ISO week to promote (YYYY-Www); default: current ISO week."

# rollup promote-month
complete -c compactor -f -n '__fish_use_subcommand' -a promote-month -d 'Rebuild a month rollup from its week rollups.'
complete -c compactor -f -n '__fish_seen_subcommand_from promote-month' -x -l month -d "Month to promote (YYYY-MM); default: current month."

# materialize
complete -c compactor -f -n '__fish_use_subcommand' -a materialize -d 'Decrypt a rollup object into a local scratch file for DuckDB.'
complete -c compactor -f -n '__fish_seen_subcommand_from materialize' -x -l out -d "Scratch directory to write the decrypted file into (default: XDG cache dir)."
complete -c compactor -f -n '__fish_seen_subcommand_from materialize' -l keep -d "Skip sweeping expired scratch files from a previous run before materializing."

# checkpoint
complete -c compactor -f -n '__fish_use_subcommand' -a checkpoint -d 'Inspect or reset checkpoint state.'

# checkpoint show
complete -c compactor -f -n '__fish_use_subcommand' -a show -d 'Print a checkpoint's current state as JSON.'
complete -c compactor -f -n '__fish_seen_subcommand_from show' -x -l day -d "Day checkpoint to target (YYYY-MM-DD)."
complete -c compactor -f -n '__fish_seen_subcommand_from show' -x -l week -d "Week checkpoint to target (YYYY-Www)."
complete -c compactor -f -n '__fish_seen_subcommand_from show' -x -l month -d "Month checkpoint to target (YYYY-MM)."

# checkpoint reset
complete -c compactor -f -n '__fish_use_subcommand' -a reset -d 'Clear a checkpoint's tracking state (operator escape hatch).'
complete -c compactor -f -n '__fish_seen_subcommand_from reset' -x -l day -d "Day checkpoint to target (YYYY-MM-DD)."
complete -c compactor -f -n '__fish_seen_subcommand_from reset' -x -l week -d "Week checkpoint to target (YYYY-Www)."
complete -c compactor -f -n '__fish_seen_subcommand_from reset' -x -l month -d "Month checkpoint to target (YYYY-MM)."
complete -c compactor -f -n '__fish_seen_subcommand_from reset' -l confirm -d "Required to actually perform the reset."

# listen
complete -c compactor -f -n '__fish_use_subcommand' -a listen -d 'Run as a long-lived event-driven daemon (NATS-triggered rollups, health probes).'

# man
complete -c compactor -f -n '__fish_use_subcommand' -a man -d 'Generate the man page.'
complete -c compactor -f -n '__fish_seen_subcommand_from man' -x -s o -l output -d "Write to this file instead of stdout."

# completions
complete -c compactor -f -n '__fish_use_subcommand' -a completions -d 'Generate a shell completion script.'

# completions bash
complete -c compactor -f -n '__fish_use_subcommand' -a bash -d 'Generate a bash completion script.'
complete -c compactor -f -n '__fish_seen_subcommand_from bash' -x -s o -l output -d "Write to this file instead of stdout."

# completions zsh
complete -c compactor -f -n '__fish_use_subcommand' -a zsh -d 'Generate a zsh completion script.'
complete -c compactor -f -n '__fish_seen_subcommand_from zsh' -x -s o -l output -d "Write to this file instead of stdout."

# completions fish
complete -c compactor -f -n '__fish_use_subcommand' -a fish -d 'Generate a fish completion script.'
complete -c compactor -f -n '__fish_seen_subcommand_from fish' -x -s o -l output -d "Write to this file instead of stdout."

